import Head from 'next/head';
import { Inter } from '@next/font/google';
import Layout from '@/components/layouts/layout';
import { Container } from '@chakra-ui/react';
import Post from '@/components/posts/post';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>IGAG</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Container maxW='container.lg' as='main'>
          {posts()}
        </Container>
      </Layout>
    </>
  );
}

function posts() {
  return [1, 3, 4].map((i) => <Post key={i} />);
}
