import Head from 'next/head';
import { Inter } from '@next/font/google';
import Layout from '@/components/layouts/layout';
import { Container } from '@chakra-ui/react';
import Post from '@/components/posts/post';
import { PrismaClient } from '@prisma/client';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>IGAG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Layout>
        <Container maxW="container.lg" as="main">
          {posts.map((post: any) => (
            <Post post={post} key={post.id} />
          ))}
        </Container>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const primsaClient = new PrismaClient({
    log: ['query'],
  });

  const posts = await primsaClient.posts.findMany();

  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
    },
  };
}
